# Generated by Django 4.2 on 2023-05-20 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTransactionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_payment_date', models.DateTimeField(auto_now_add=True)),
                ('user_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_transaction_type', models.CharField(choices=[('Semester Fee', 'Semester Fee'), ('College Fee', 'College Fee')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_test_type', models.CharField(choices=[('NEET', 'NEET')], max_length=20)),
                ('user_test_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_test_date', models.DateField()),
                ('user_test_exp_date', models.DateField()),
                ('user_test_document_image', models.ImageField(blank=True, upload_to='test_score_image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_address', models.CharField(blank=True, max_length=100)),
                ('user_password', models.CharField(max_length=100)),
                ('user_phone', models.CharField(max_length=20, unique=True)),
                ('user_converted', models.BooleanField(default=False)),
                ('user_father_name', models.CharField(blank=True, max_length=50)),
                ('user_dob', models.DateField(blank=True, null=True)),
                ('user_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_college_preference', models.CharField(blank=True, max_length=100)),
                ('user_profile_image', models.ImageField(blank=True, upload_to='user_profile_images')),
                ('user_status', models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=20)),
                ('user_created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Accounts.userprofile')),
                ('user_test_info', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Accounts.usertestinfo')),
                ('user_transaction', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Accounts.usertransactiontable')),
            ],
        ),
    ]
