# Generated by Django 4.2 on 2023-05-20 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user_transaction',
        ),
    ]
