# Generated by Django 4.2 on 2023-05-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_remove_account_user_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_password',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
