# Generated by Django 4.2 on 2023-05-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_remove_userprofile_user_password_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile_images'),
        ),
        migrations.AlterField(
            model_name='usertestinfo',
            name='user_test_document_image',
            field=models.ImageField(blank=True, null=True, upload_to='test_score_image'),
        ),
    ]
