# Generated by Django 4.2 on 2023-06-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
