# Generated by Django 4.2 on 2023-06-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_alter_userprofile_user_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertestinfo',
            name='user_test_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertestinfo',
            name='user_test_exp_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertestinfo',
            name='user_test_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
