# Generated by Django 4.2 on 2023-06-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_alter_usertestinfo_user_test_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
