# Generated by Django 4.2 on 2023-06-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_alter_user_username_alter_userprofile_user_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
