# Generated by Django 4.0.3 on 2024-05-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
