# Generated by Django 4.2 on 2024-07-17 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0015_userprofile_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_bio',
        ),
    ]
