# Generated by Django 4.2 on 2023-05-22 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=50)),
                ('college_slug', models.SlugField()),
                ('college_email', models.EmailField(max_length=254)),
                ('college_country', models.CharField(max_length=50)),
                ('college_phone', models.CharField(max_length=13)),
                ('college_contact', models.CharField(max_length=50)),
                ('college_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='college_images')),
            ],
        ),
        migrations.CreateModel(
            name='CollegeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_address', models.CharField(max_length=200)),
                ('college_fee_total', models.IntegerField()),
                ('college_course_offered', models.CharField(max_length=200)),
                ('college_required_twelth_marks', models.FloatField()),
                ('college_exam_accepted', models.CharField(max_length=100)),
                ('college_scholarship', models.PositiveIntegerField()),
                ('college_course_duration', models.PositiveIntegerField()),
                ('college_description', models.TextField()),
                ('college_intake_session', models.CharField(max_length=30)),
                ('college_yt_video', models.URLField()),
                ('college', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='info', to='Colleges.college')),
                ('college_media', models.ManyToManyField(blank=True, null=True, related_name='colleges', to='Colleges.collegemedia')),
            ],
        ),
    ]
