# Generated by Django 4.2 on 2023-05-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colleges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeinfo',
            name='college_media',
            field=models.ManyToManyField(blank=True, related_name='colleges', to='Colleges.collegemedia'),
        ),
    ]
