# Generated by Django 4.2 on 2024-07-17 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Colleges', '0002_alter_collegeinfo_college_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuition_fees', models.JSONField(default=dict, null=True)),
                ('one_time_charges', models.JSONField(default=dict, null=True)),
                ('hostel_fees', models.JSONField(default=dict, null=True)),
                ('totals', models.JSONField(default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('established_year', models.IntegerField(null=True)),
                ('previous_name', models.CharField(blank=True, max_length=255, null=True)),
                ('course_duration_years', models.IntegerField(null=True)),
                ('medium_of_instruction', models.CharField(max_length=255, null=True)),
                ('temperature_range_july', models.CharField(max_length=50, null=True)),
                ('temperature_range_january', models.CharField(max_length=50, null=True)),
                ('visa_success_ratio', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('study_material_worth', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('hostel_facility', models.BooleanField(null=True)),
                ('crime_free_campus', models.BooleanField(null=True)),
                ('ragging_free_campus', models.BooleanField(null=True)),
                ('no_donation', models.BooleanField(null=True)),
                ('separate_hostel_girls_boys', models.BooleanField(null=True)),
                ('hot_water_supply', models.BooleanField(null=True)),
                ('room_heating_system', models.BooleanField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='collegeinfo',
            name='colege_fee_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fee', to='Colleges.feestructure'),
        ),
        migrations.AddField(
            model_name='collegeinfo',
            name='college_extra_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='extra_info', to='Colleges.university'),
        ),
    ]
