# Generated by Django 4.2 on 2024-07-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colleges', '0003_feestructure_university_collegeinfo_colege_fee_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
