# Generated by Django 4.2 on 2024-07-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colleges', '0004_feestructure_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='course_duration_years',
        ),
        migrations.RemoveField(
            model_name='university',
            name='hot_water_supply',
        ),
        migrations.RemoveField(
            model_name='university',
            name='previous_name',
        ),
        migrations.RemoveField(
            model_name='university',
            name='ragging_free_campus',
        ),
        migrations.RemoveField(
            model_name='university',
            name='room_heating_system',
        ),
        migrations.RemoveField(
            model_name='university',
            name='separate_hostel_girls_boys',
        ),
        migrations.RemoveField(
            model_name='university',
            name='temperature_range_january',
        ),
        migrations.RemoveField(
            model_name='university',
            name='temperature_range_july',
        ),
        migrations.AddField(
            model_name='university',
            name='extra_university_info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='temperature_range',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='crime_free_campus',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='established_year',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='hostel_facility',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='medium_of_instruction',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='no_donation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='study_material_worth',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='visa_success_ratio',
            field=models.TextField(null=True),
        ),
    ]
