# Generated by Django 4.2 on 2024-07-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colleges', '0005_remove_university_course_duration_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='crime_free_campus',
            field=models.TextField(default='No crime, ragging free campus', null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='extra_university_info',
            field=models.TextField(default='Quality Education', null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='hostel_facility',
            field=models.TextField(default='Best Hostel Facility', null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='no_donation',
            field=models.TextField(default='No Donation', null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='study_material_worth',
            field=models.TextField(default='No Entrance Exam', null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='visa_success_ratio',
            field=models.TextField(default='100 % Visa Success Ratio', null=True),
        ),
    ]
